"""
FreightGenie — Phase 2: Business Insights PDF Report
Run: python3 insights_report.py

Reads insights.json + the chart PNGs (already generated by analysis.py)
and assembles them into a single, professional PDF — the kind of report
a freight forwarding company's management would actually read.

This intentionally mirrors the navy letterhead / footer style used by
the Node.js PDF reports (pdfHelpers.js) so all of FreightGenie's
documents look like they come from the same product.
"""

import os
import json
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image,
    PageBreak, HRFlowable,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_RIGHT, TA_CENTER
from dotenv import load_dotenv

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(BASE_DIR, ".env"))

CHARTS_DIR = os.path.join(BASE_DIR, os.environ.get("ANALYTICS_CHARTS_DIR", "charts"))
INSIGHTS_JSON = os.path.join(BASE_DIR, os.environ.get("ANALYTICS_INSIGHTS_FILE", "insights.json"))
OUTPUT_PDF = os.path.join(BASE_DIR, os.environ.get("ANALYTICS_REPORT_FILE", "business_insights_report.pdf"))
DEFAULT_COMPANY_NAME = os.environ.get("ANALYTICS_COMPANY_NAME", "FreightGenie")

# ── Brand colors (matches services/pdfHelpers.js) ─────────────────
NAVY = colors.HexColor("#1e3a5f")
MUTED = colors.HexColor("#64748b")
BORDER = colors.HexColor("#e2e8f0")
SUCCESS = colors.HexColor("#16a34a")
WARNING = colors.HexColor("#d97706")
DANGER = colors.HexColor("#dc2626")
ROW_ALT = colors.HexColor("#f8fafc")

TYPE_COLOR = {
    "growth": SUCCESS,
    "cargo": colors.HexColor("#2563eb"),
    "success": SUCCESS,
    "warning": WARNING,
}

TYPE_ICON = {
    "growth": "UP",
    "cargo": "CARGO",
    "success": "OK",
    "warning": "ALERT",
}


def load_insights():
    if not os.path.exists(INSIGHTS_JSON):
        print(f"X insights.json not found at {INSIGHTS_JSON}")
        print("  Run analysis.py first.")
        exit(1)
    with open(INSIGHTS_JSON) as f:
        return json.load(f)


def build_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("ReportTitle", fontName="Helvetica-Bold", fontSize=17, textColor=colors.white, alignment=TA_RIGHT, leading=20))
    styles.add(ParagraphStyle("CompanyName", fontName="Helvetica-Bold", fontSize=16, textColor=colors.white))
    styles.add(ParagraphStyle("HeaderMeta", fontName="Helvetica", fontSize=9, textColor=colors.HexColor("#cbd5e1"), alignment=TA_RIGHT))
    styles.add(ParagraphStyle("RefMeta", fontName="Helvetica", fontSize=9, textColor=MUTED))
    styles.add(ParagraphStyle("SectionTitle", fontName="Helvetica-Bold", fontSize=13, textColor=NAVY, spaceBefore=14, spaceAfter=6))
    styles.add(ParagraphStyle("InsightTitle", fontName="Helvetica-Bold", fontSize=10, textColor=colors.HexColor("#1e293b")))
    styles.add(ParagraphStyle("InsightDetail", fontName="Helvetica", fontSize=9, textColor=MUTED, spaceAfter=2))
    styles.add(ParagraphStyle("InsightAction", fontName="Helvetica-Bold", fontSize=9))
    styles.add(ParagraphStyle("Footer", fontName="Helvetica", fontSize=8, textColor=MUTED))
    styles.add(ParagraphStyle("FooterRight", fontName="Helvetica", fontSize=8, textColor=MUTED, alignment=TA_RIGHT))
    styles.add(ParagraphStyle("ChartCaption", fontName="Helvetica-Bold", fontSize=10, textColor=NAVY, spaceBefore=10, spaceAfter=4, alignment=TA_CENTER))
    return styles


def letterhead_table(styles, company_name, report_ref):
    """Navy band header, same idea as drawLetterhead() in pdfHelpers.js"""
    title_block = [
        Paragraph("FREIGHT FORWARDING", styles["HeaderMeta"]),
        Paragraph("Business Insights Report", styles["ReportTitle"]),
    ]
    header = Table(
        [[Paragraph(company_name, styles["CompanyName"]), title_block]],
        colWidths=[90 * mm, 90 * mm],
    )
    header.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
    ]))

    meta = Table(
        [[
            Paragraph(f"Reference: {report_ref}", styles["RefMeta"]),
            Paragraph(f"Generated: {datetime.now().strftime('%d %b %Y, %H:%M')}", styles["FooterRight"]),
        ]],
        colWidths=[90 * mm, 90 * mm],
    )
    meta.setStyle(TableStyle([
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))

    return [header, meta]


def stats_table(styles, stats):
    rows = [
        ["Metric", "Value"],
        ["Total Shipments Analyzed", str(stats["totalShipments"])],
        ["Average Compliance Score", f"{stats['avgComplianceScore']} / 100"],
        ["High Risk Shipments", str(stats["highRiskCount"])],
        ["Average Missing Documents per Shipment", str(stats["avgMissingDocs"])],
        ["Top Performing Route", stats["topRoute"]],
        ["Dominant Cargo Type", stats["topCargo"]],
    ]
    t = Table(rows, colWidths=[110 * mm, 70 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ROW_ALT]),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return t


def insight_block(styles, insight):
    color = TYPE_COLOR.get(insight["type"], colors.HexColor("#1e3a5f"))
    tag = TYPE_ICON.get(insight["type"], "INFO")

    cell = [
        Paragraph(f"<font color='{color.hexval()}'>[{tag}]</font>  {insight['title']}", styles["InsightTitle"]),
        Spacer(1, 2),
        Paragraph(insight["detail"], styles["InsightDetail"]),
        Paragraph(f"<font color='{color.hexval()}'>Recommended Action:</font> {insight['action']}", styles["InsightAction"]),
    ]
    t = Table([[cell]], colWidths=[180 * mm])
    t.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 1, color),
        ("LINEBEFORE", (0, 0), (0, -1), 3, color),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (-1, -1), colors.white),
    ]))
    return t


def chart_image(path, max_width_mm=170):
    if not os.path.exists(path):
        return None
    img = Image(path)
    aspect = img.imageHeight / float(img.imageWidth)
    img.drawWidth = max_width_mm * mm
    img.drawHeight = img.drawWidth * aspect
    return img


def footer(canvas, doc, report_ref):
    canvas.saveState()
    width, height = A4
    margin = 14 * mm
    y = 16 * mm

    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(margin, y + 6, width - margin, y + 6)

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawString(margin, y, "CONFIDENTIAL — Internal Business Report")
    canvas.drawRightString(
        width - margin, y,
        f"Ref: {report_ref}  |  Generated: {datetime.now().strftime('%d %b %Y %H:%M')}  |  Page {doc.page}",
    )
    canvas.restoreState()


def build_report(company_name=DEFAULT_COMPANY_NAME, report_ref=None):
    data = load_insights()
    stats = data["stats"]
    insights = data["insights"]

    if report_ref is None:
        report_ref = f"BI-{datetime.now().strftime('%Y%m%d')}"

    styles = build_styles()
    doc = SimpleDocTemplate(
        OUTPUT_PDF, pagesize=A4,
        leftMargin=14 * mm, rightMargin=14 * mm,
        topMargin=10 * mm, bottomMargin=22 * mm,
    )

    elements = []

    # ── Letterhead ──
    elements += letterhead_table(styles, company_name, report_ref)
    elements.append(Spacer(1, 10))

    # ── Executive Summary ──
    elements.append(Paragraph("Executive Summary", styles["SectionTitle"]))
    elements.append(Paragraph(
        f"This report analyzes <b>{stats['totalShipments']}</b> shipments processed through FreightGenie, "
        f"covering routes, cargo mix, compliance performance, and cost trends. "
        f"The average compliance score across all shipments is <b>{stats['avgComplianceScore']}/100</b>, "
        f"with <b>{stats['highRiskCount']}</b> shipments flagged as high risk.",
        styles["InsightDetail"]
    ))
    elements.append(Spacer(1, 8))
    elements.append(stats_table(styles, stats))

    # ── Business Recommendations ──
    elements.append(Paragraph("Business Recommendations", styles["SectionTitle"]))
    for ins in insights:
        elements.append(insight_block(styles, ins))
        elements.append(Spacer(1, 6))

    # ── Charts ──
    elements.append(PageBreak())
    elements.append(Paragraph("Detailed Analysis — Charts", styles["SectionTitle"]))

    chart_files = [
        ("Route Analysis — Top Routes by Shipment Volume", "01_route_analysis.png"),
        ("Cargo Type Distribution", "02_cargo_type.png"),
        ("Monthly Shipment Volume & Compliance Trend", "03_monthly_trend.png"),
        ("Compliance Score Distribution", "04_compliance_score.png"),
        ("Risk Levels & Missing Documents Pattern", "05_missing_docs.png"),
        ("Shipping Mode Breakdown", "06_shipping_mode.png"),
    ]

    for i, (caption, filename) in enumerate(chart_files):
        img = chart_image(os.path.join(CHARTS_DIR, filename))
        if img is None:
            continue
        elements.append(Paragraph(caption, styles["ChartCaption"]))
        elements.append(img)
        if i < len(chart_files) - 1:
            elements.append(HRFlowable(width="100%", color=BORDER, thickness=0.5, spaceBefore=10, spaceAfter=4))

    # ── Closing note ──
    elements.append(PageBreak())
    elements.append(Paragraph("About This Report", styles["SectionTitle"]))
    elements.append(Paragraph(
        "This report was generated automatically by FreightGenie's analytics module using "
        "Pandas for data aggregation, NumPy for statistical calculations, and Seaborn/Matplotlib "
        "for visualization. Data is sourced from completed shipment compliance reviews and is "
        "updated each time the analysis is refreshed.",
        styles["InsightDetail"]
    ))

    def on_page(canvas, doc_):
        footer(canvas, doc_, report_ref)

    doc.build(elements, onFirstPage=on_page, onLaterPages=on_page)
    print(f"OK Business Insights report saved: {OUTPUT_PDF}")
    return OUTPUT_PDF


if __name__ == "__main__":
    build_report()
